// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvFnPGW_1hm6dwzdVJs3SIRVYtim6WB4',
    appId: '1:1093583695793:web:6dd07da2e104fec1231790',
    messagingSenderId: '1093583695793',
    projectId: 'chat-a-55869',
    authDomain: 'chat-a-55869.firebaseapp.com',
    storageBucket: 'chat-a-55869.firebasestorage.app',
    measurementId: 'G-6D5BDXJ8GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6DnNVFHHDXmehcssHCQ69qX1tINr-nc',
    appId: '1:1093583695793:android:15b0214e6ba6b338231790',
    messagingSenderId: '1093583695793',
    projectId: 'chat-a-55869',
    storageBucket: 'chat-a-55869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxWUQaI97N3s_tOxzLFGywFuSIF4anZVM',
    appId: '1:1093583695793:ios:5bb087e7a84948ac231790',
    messagingSenderId: '1093583695793',
    projectId: 'chat-a-55869',
    storageBucket: 'chat-a-55869.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxWUQaI97N3s_tOxzLFGywFuSIF4anZVM',
    appId: '1:1093583695793:ios:5bb087e7a84948ac231790',
    messagingSenderId: '1093583695793',
    projectId: 'chat-a-55869',
    storageBucket: 'chat-a-55869.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvFnPGW_1hm6dwzdVJs3SIRVYtim6WB4',
    appId: '1:1093583695793:web:f1024d623a40007f231790',
    messagingSenderId: '1093583695793',
    projectId: 'chat-a-55869',
    authDomain: 'chat-a-55869.firebaseapp.com',
    storageBucket: 'chat-a-55869.firebasestorage.app',
    measurementId: 'G-P3B59RB1XR',
  );

}