// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSLOjcsE58Bc2Uzh1xFqSeCoX6pCnz4Zk',
    appId: '1:395386952731:web:33fca43f4f8c4ce771ecbe',
    messagingSenderId: '395386952731',
    projectId: 'chat-app-333ea',
    authDomain: 'chat-app-333ea.firebaseapp.com',
    storageBucket: 'chat-app-333ea.firebasestorage.app',
    measurementId: 'G-3SV7S5ERJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIjj_oZtDuEIJeauoZ-N3iV39hjbNMbs',
    appId: '1:395386952731:android:c3a294bdb332c22a71ecbe',
    messagingSenderId: '395386952731',
    projectId: 'chat-app-333ea',
    storageBucket: 'chat-app-333ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCphE6fRnPQoA4z9u0YSRoKolFc1c3I0u0',
    appId: '1:395386952731:ios:287700526b9302d471ecbe',
    messagingSenderId: '395386952731',
    projectId: 'chat-app-333ea',
    storageBucket: 'chat-app-333ea.firebasestorage.app',
    iosBundleId: 'com.example.testFireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCphE6fRnPQoA4z9u0YSRoKolFc1c3I0u0',
    appId: '1:395386952731:ios:287700526b9302d471ecbe',
    messagingSenderId: '395386952731',
    projectId: 'chat-app-333ea',
    storageBucket: 'chat-app-333ea.firebasestorage.app',
    iosBundleId: 'com.example.testFireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSLOjcsE58Bc2Uzh1xFqSeCoX6pCnz4Zk',
    appId: '1:395386952731:web:f4a0d7ba614b0c4a71ecbe',
    messagingSenderId: '395386952731',
    projectId: 'chat-app-333ea',
    authDomain: 'chat-app-333ea.firebaseapp.com',
    storageBucket: 'chat-app-333ea.firebasestorage.app',
    measurementId: 'G-8ZEHC7QJFM',
  );

}